version: 2 #dependabot config version
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "securitiessss"
    reviewers:
      - "sonali-varshney"
      - "Copilot"

  - package-ecosystem: "maven"  #type of package or dependency
    directory: "/"              #dependency file location.So pom.xml is present at root so /
    schedule:
      interval: "daily"         #when to run dependabot. it can be weekly,daily
      day: "monday"             #to run on a specific day
    labels:
      - "dependencies"
      - "securitiessss"

  - package-ecosystem: "docker"
    directory: "/infra"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
